# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a88b53e67f42deb34445fff52bd25a5e3274670808f8ca129f7ff0c5a1768e92f89995bef74387b3adaca201a81ee1b5871ddc22a582e024a0cac5ede5815d38

test:
  secret_key_base: 38cbfb3cde5c1f6b0660b7b4b4a40e14d9b7853a43595eaca64701e308050ae204eedde723719a643174cbd8f7470e3a2c338a17e5f15c5df0eaa8ba6798d026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
